### ISSUE TITLE
[TEOTB-5][Dev-Ops] Ready to Cloud-based solution 

### ISSUE THREAD

**Issue by Ghbdtn-Kthf** [DonkeyRit/friendly-spoon#5]
- [ ] Build application through Maven;
- [ ] Add pull-request builder within Github Actions.

**Comment by DonkeyRit** [comment]
# GitHub Actions
GitHub Actions is a continuous integration and continuous delivery (CI/CD) platform that allows you to automate your build, test, and deployment pipeline. You can create workflows that build and test every pull request to your repository, or deploy merged pull requests to production.

##### Links:
- [Understanding GitHub Actions](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#overview)
